"""Tor Service Config"""
TOR_SOCKS_PORT=9050
TOR_CONTROL_PORT=9051
HIDDEN_SERVICE_DIR="/var/lib/tor/hidden_service"
HIDDEN_SERVICE_PORT=80
CIRCUIT_BUILD_TIMEOUT=60
NEW_CIRCUIT_PERIOD=30
SAFE_MODE=True
